### ISSUE TITLE
suggestion: Define wellknown license

### ISSUE THREAD

**Issue by neon-izm** [bexide/BxUni-MissingFinder#1]
現在のライセンス表記は元著作権の保持者のクレジットのみが表示されている状態で、利用者はどのような責務を持つかが分かりにくいです。

たとえば MITライセンスやApacheライセンスなど、広く使われているライセンスか、あるいは独自のライセンスがあるかをリポジトリ内に明記してもらえると嬉しいです。

**Comment by hayashi-bxj** [comment]
ご指摘ありがとうございます。
元よりMITライセンスを想定しておりましたが記述を失念しておりました。
修正致しました。

**Comment by neon-izm** [comment]
ありがとうございます！！（これは雑談ですがスーパーバレットブレイクをSteamDeckで遊んでいます。とても楽しかったです）
